_make a word count of each of word  repeating in Vocabulary_

**Limitation of Bag Of Words**<br>
_It consume much memory, yes it is less than One Hot Encoding {It is Sparse Representation : It is vector in which most of the values are 0}_
<br>
_It does not capture meaning of words properly_
<br>



In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("spam.csv")

In [3]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()
# in pandas we can use value_counts() method for counting values of all features present in particular columns

ham     4825
spam     747
Name: Category, dtype: int64

In [5]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.Message,df.spam,test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train) 
# it is pandas seris 

pandas.core.series.Series

In [13]:
X_train[:4][1894]
# this is full mail of 1894

'Good Morning plz call me sir'

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:10]

1894    0
2768    0
4963    0
5553    0
4858    0
299     0
3477    0
4021    0
1976    0
1708    0
Name: spam, dtype: int64

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [17]:
v=CountVectorizer()

In [18]:
#we can see different method present in v by using 
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'de

In [19]:
X_train_cv=v.fit_transform(X_train.values)
#here we are giving .values because it will convert array into numpy array which can be read by machine 


In [20]:
X_train_cv

<4457x7830 sparse matrix of type '<class 'numpy.int64'>'
	with 59551 stored elements in Compressed Sparse Row format>

In [21]:
X_train_cv.shape
# ther are 7770 different words present and total emails are 4457 

(4457, 7830)

In [22]:
v.vocabulary_
# for getting vocabulary

{'good': 3212,
 'morning': 4646,
 'plz': 5327,
 'call': 1627,
 'me': 4458,
 'sir': 6247,
 'wow': 7698,
 'impressed': 3684,
 'have': 3390,
 'funs': 3074,
 'shopping': 6174,
 'yup': 7814,
 'ok': 4988,
 'hahaha': 3324,
 'use': 7283,
 'your': 7796,
 'brain': 1497,
 'dear': 2216,
 'thanks': 6861,
 'and': 970,
 'or': 5047,
 'bomb': 1442,
 'date': 2195,
 'as': 1098,
 'my': 4725,
 'phone': 5253,
 'wanted': 7448,
 'to': 6994,
 'say': 5992,
 'cant': 1663,
 'pick': 5265,
 'the': 6872,
 'right': 5856,
 'now': 4908,
 'pls': 5321,
 'send': 6075,
 'message': 4510,
 'can': 1652,
 'probably': 5499,
 'come': 1933,
 'by': 1610,
 'everybody': 2698,
 'done': 2431,
 'around': 1084,
 'lt': 4298,
 'gt': 3288,
 'university': 7226,
 'of': 4964,
 'southern': 6409,
 'california': 1626,
 'delhi': 2259,
 'chennai': 1794,
 'still': 6546,
 'silent': 6226,
 'was': 7459,
 'doing': 2421,
 'test': 6840,
 'earlier': 2528,
 'appreciate': 1043,
 'you': 7790,
 'will': 7595,
 'tomorrow': 7021,
 'already': 933,
 'one': 5011,
 

In [23]:
v.get_feature_names_out()[3000]
#using .get_feature_names_out we can get particular word from vocabulary 

'fps'

In [24]:
X_train_cv.toarray()[:2]
# we are converting back to array for our reference that we can see the data correctly

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [25]:
X_train_np=X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
np.where(X_train_np[0]!=0) # np.where is used to find particular data 
# this is the vector representation of first email in x_train_np where 0 is not there in vector

(array([1627, 3212, 4458, 4646, 5327, 6247], dtype=int64),)

In [27]:
X_train[:4]

1894              Good Morning plz call me sir
2768    Wow v v impressed. Have funs shopping!
4963                                 Yup ok...
5553               Hahaha..use your brain dear
Name: Message, dtype: object

In [29]:
X_train[:4][1894]
#this is the first email of X_train 

'Good Morning plz call me sir'

In [30]:
# now we are searching particular encoded word of 1st email of x_train in Vocabulary
v.get_feature_names_out()[1436]
# so here we find that word bored is numbered as 1436 in vocabulary 

'body'

* now are going to apply machine learning model
* Naive bayes model

In [32]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv,y_train)
#cv means count Vectorizer 

MultinomialNB()

In [33]:
#For testing purpose we are first converting X_test data to count vectorizer so that we can test it 
X_test_cv = v.transform(X_test)

In [80]:
from sklearn.metrics import classification_report
y_pred = model.predict(X_test_cv)
classification_report1=classification_report(y_test,y_pred)
type(y_pred)

numpy.ndarray

In [81]:
print(classification_report1)
# we are using classification report which has precision ,recall and f1- score because our dataset was unbalanced

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.97      0.95      0.96       150

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



**now let's predict email is spam or not by writting email our own**

In [82]:
emails = ["hey meet can we connect on Linkedin" ,
          "hey you won lottery of 50000$ free of cost"
          ]

In [83]:
#transforming mail into count vectorizer
email_count = v.transform(emails)

In [84]:
#now we are predicting email is spam or not 
model.predict(email_count)

array([0, 1], dtype=int64)

* we find that first email is not spam but second email is spam and in reality it seems to be spam so our model has predicted accurately

**we can do  this all steps easily using sklearn pipeline**

In [85]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [86]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [87]:
y_pred = clf.predict(X_test)
type(y_pred)

numpy.ndarray

In [88]:
classification_report2 = classification_report(y_test,y_pred)

In [90]:
print(classification_report2)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.97      0.95      0.96       150

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

